### ISSUE TITLE
Fix the UI 

### ISSUE THREAD

**Issue by rahulsingh2312** [rahulsingh2312/RandomTaylorSwiftSong#1]
Create a better ui

**Comment by tushar1-000** [comment]
Do you have any designs for this. Or I should design it by myself by taking inspiration from web.

**Comment by rahulsingh2312** [comment]
> Do you have any designs for this. Or I should design it by myself by taking inspiration from web.

design yourself but make sure to think about leaving space for preview or the song which will be played by the user

**Comment by tushar1-000** [comment]
Ok I will keep in mind you can assign to me.

**Comment by rahulsingh2312** [comment]
> Ok I will keep in mind you can assign to me.
> 

hi @tushar1-000 ![PXL_20231003_222712661.MP.jpg](https://github.com/rahulsingh2312/RandomTaylorSwiftSong/assets/111289008/2a07134c-1a32-4fbd-8984-5bbe482859e8)

so this are the components of the website pls consider this while making the Ui

**Comment by rizzabh** [comment]
![Screenshot 2023-10-04 214334](https://github.com/rahulsingh2312/RandomTaylorSwiftSong/assets/133371863/4103536b-7a7e-48d3-9fcd-b32fe98d5ed2)

Looks cool?
