### ISSUE TITLE
Making a preview or demo of the song

### ISSUE THREAD

**Issue by rahulsingh2312** [rahulsingh2312/RandomTaylorSwiftSong#2]
we are doing it using youtube api now lol

**Comment by tushar1-000** [comment]
Hi, I want to work on this issue. Can you elaborate on what type of preview or demo you want.

**Comment by rahulsingh2312** [comment]
> Hi, I want to work on this issue. Can you elaborate on what type of preview or demo you want.

it should play that song which it suggests

**Comment by rahulsingh2312** [comment]
done
